# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mailgenerate.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets
import random
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Random Mail Generator")
        MainWindow.resize(449, 464)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gmailButton = QtWidgets.QRadioButton(self.centralwidget)
        self.gmailButton.setGeometry(QtCore.QRect(20, 260, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gmailButton.setFont(font)
        self.gmailButton.setObjectName("gmailButton")
        self.hotmailButton = QtWidgets.QRadioButton(self.centralwidget)
        self.hotmailButton.setGeometry(QtCore.QRect(20, 300, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hotmailButton.setFont(font)
        self.hotmailButton.setObjectName("hotmailButton")
        self.protonButton = QtWidgets.QRadioButton(self.centralwidget)
        self.protonButton.setGeometry(QtCore.QRect(20, 340, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.protonButton.setFont(font)
        self.protonButton.setObjectName("protonButton")
        self.gmailButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.gmailButton_4.setGeometry(QtCore.QRect(20, 380, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.gmailButton_4.setFont(font)
        self.gmailButton_4.setObjectName("gmailButton_4")
        self.generatedMails = QtWidgets.QTextEdit(self.centralwidget)
        self.generatedMails.setGeometry(QtCore.QRect(190, 260, 241, 141))
        self.generatedMails.setObjectName("generatedMails")
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setGeometry(QtCore.QRect(210, 40, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.generateButton.setFont(font)
        self.generateButton.setObjectName("generateButton")

        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(210, 100, 211, 41))
        self.clear_button.setFont(font)
        self.clear_button.setObjectName("clearbutton")



       
        font = QtGui.QFont()
        font.setPointSize(20)
        
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 40, 141, 211))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout.addWidget(self.nameLabel)
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.surnameLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.surnameLabel.setFont(font)
        self.surnameLabel.setObjectName("surnameLabel")
        self.verticalLayout.addWidget(self.surnameLabel)
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.countLabel = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.countLabel.setFont(font)
        self.countLabel.setObjectName("countLabel")
        self.verticalLayout.addWidget(self.countLabel)
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout.addWidget(self.textEdit_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 449, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.generateButton.clicked.connect(self.getText)
        self.clear_button.clicked.connect(self.clear_text_field)
 
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Random Mail Generator"))
        self.gmailButton.setText(_translate("MainWindow", "Gmail"))
        self.hotmailButton.setText(_translate("MainWindow", "Hotmail"))
        self.protonButton.setText(_translate("MainWindow", "Protonmail"))
        self.gmailButton_4.setText(_translate("MainWindow", "Yandex mail"))
        self.generateButton.setText(_translate("MainWindow", "Generate"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))
        
        self.nameLabel.setText(_translate("MainWindow", "Name"))
        self.surnameLabel.setText(_translate("MainWindow", "Surname"))
        self.countLabel.setText(_translate("MainWindow", "Mail Count"))

    def getText(self):

        name_text = self.textEdit.toPlainText()
        surname_text = self.textEdit_2.toPlainText()
        mail_count = self.textEdit_3.toPlainText()
        

        if self.gmailButton.isChecked():
            for x in range(int(mail_count)):
                random_number = random.randint(0,10000)
                self.generatedMails.append(name_text + surname_text + str(random_number) + "@gmail.com")
                
        elif self.hotmailButton.isChecked():
            for x in range(int(mail_count)):
                random_number = random.randint(0,10000)
                self.generatedMails.append(name_text + surname_text + str(random_number) + "@hotmail.com")
                
        elif self.protonButton.isChecked():
            for x in range(int(mail_count)):
                random_number = random.randint(0,10000)
                self.generatedMails.append(name_text + surname_text + str(random_number) + "@proton.com")

        elif self.gmailButton_4.isChecked():
            for x in range(int(mail_count)):
                random_number = random.randint(0,10000)
                self.generatedMails.append(name_text + surname_text + str(random_number) + "@yandex.com")
            
        

    def clear_text_field(self):
        self.generatedMails.clear()
    
   

        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
